
//
// This file is automatically generated
//
namespace Trion
{





public enum TrionCommand
{

OPEN_BOARD = 0x0001,  // Set
CLOSE_BOARD = 0x0002,  // Set
RESET_BOARD = 0x0003,  // Set
START_ACQUISITION = 0x0004,  // Get / Set
STOP_ACQUISITION = 0x0005,  // Set
ACT_SAMPLE_COUNT = 0x000A,  // Get      Read Register ADC_SCNT

UPDATE_PARAM_ALL = 0x0010,  // Set
UPDATE_PARAM_ACQ_ALL = 0x0011,  // Set
UPDATE_PARAM_CHN_ALL = 0x0012,  // Set
UPDATE_PARAM_ACQ = 0x0013,  // Set
UPDATE_PARAM_MUX = 0x0014,  // Set
UPDATE_PARAM_INTSIG0 = 0x0015,  // Set
UPDATE_PARAM_INTSIG1 = 0x0016,  // Set
UPDATE_PARAM_AI = 0x0017,  // Set
UPDATE_PARAM_CNT = 0x0018,  // Set
UPDATE_PARAM_DI = 0x0019,  // Set
UPDATE_PARAM_BOARD_CNT = 0x001A,  // Set
UPDATE_PARAM_CAN = 0x001B,  // Set
UPDATE_PARAM_UART = 0x0052,  // Set
ASYNC_POLLING_TIME = 0x001C,  // Set
ASYNC_FRAME_SIZE = 0x001D,  // Set
UPDATE_PARAM_ACQ_TIMING = 0x001E,  // Set
TIMING_STATE = 0x001F,  // Set

BUFFER_START_POINTER = 0x0020,  // Get
BUFFER_END_POINTER = 0x0021,  // Get
BUFFER_CLEAR_ERROR = 0x0022,  // Set
BUFFER_AVAIL_NO_SAMPLE = 0x0025,  // Get
BUFFER_ACT_SAMPLE_POS = 0x0026,  // Get
BUFFER_FREE_NO_SAMPLE = 0x0027,  // Set
BUFFER_TOTAL_MEM_SIZE = 0x0028,  // Get
BUFFER_ONE_BLOCK_SIZE = 0x0029,  // Get
BUFFER_ONE_SCAN_SIZE = 0x002A,  // Get

GET_UART_STATUS = 0x0030,  // Get
BUFFER_WAIT_AVAIL_NO_SAMPLE = 0x0031,  // Get
ACQ_STATE = 0x0032,  // Get
UPDATE_PARAM_AREF = 0x0033,  // Set
TIMING_TIME = 0x0034,  // Get
GPS_RECEIVER_RESET = 0x0035,  //Set

PXI_LINE_STATE = 0x0040,  // Get

DISCRET_STATE_SET = 0x0050,  // Set
DISCRET_STATE_CLEAR = 0x0051,  // Set

DISCRET_GROUP32_SET = 0x0060,  // Set (will set all 32 Bits of a grou, will have encoded groupinfo in lowernibble ( x60, x61, x62,...)

IDLED_BOARD_ON = 0x0070,  // Set
IDLED_BOARD_OFF = 0x0071,  // Set
IDLED_CHANNEL_ON = 0x0072,  // Set
IDLED_CHANNEL_OFF = 0x0073,  // Set


BUFFER_BLOCK_SIZE = 0x0102,  // Set
BUFFER_BLOCK_COUNT = 0x0107,  //
GETDATA_TIME_OUT = 0x0A01,  // Get
UPDATE_PARAM_ACQ_ROUTE = 0x0103,  // Set
INT_REF_VAL = 0x0201,  // Set / Get
REF_MODE = 0x0202,  // Set / Get
UPDATE_PARAM_INTCAL = 0x0205,  // Set
BOARD_ACT_SAMPLE_COUNT = 0x0301,  // R        Read Register ADC_SCNT TBD: 64Bit command
BOARD_ADC_DELAY = 0x0302,  // R        Obtain ADC-Delay (valid only AFTER setting a samplerate)
BOARD_AFSPAN = 0x0303,  // R        Query %of Samplerate that is alias free
BOARD_RESET_SELFCAL = 0x0305,  // W        Reset the whole Selfcal-Section in BaseE2Prom with the Default-values
BOARD_BASEEEPROM_WRITE = 0x0401,  // W        Write the BaseEEprom-File to EEProm
BOARD_CONEEPROM_WRITE = 0x0402,  // W        Write the ConnectorEEprom-File to EEProm
BOARD_BASEEEPROM_SELFCAL_WRITE = 0x0403,  // W        Write the BaseEEprom-File to EEProm
BOARD_BASEEEPROM_RESTORE_BACKUP = 0x0404,  // W        Try to restore a backup for base e2prom
BOARD_CONEEPROM_RESTORE_BACKUP = 0x0405,  // W        Try to restore a backup for con e2prom
BOARD_AITEDSEX_READ = 0x0406,  // R        Reads the AiTEDSEx data from the TEDS chip
BOARD_AITEDSEX_WRITE = 0x0407,  // W        Write the AiTEDSEx data back to the TEDS chip
BOARD_AITEDSEX_SYNCHRONIZE = 0x0408,  // U        Synchronizes raw TEDS memory data with updated TEDSInfo data


BOARD_REINIT = 0x0420,  // Set

OPEN_BOARD_ALL = 0x0450,  // Set
CLOSE_BOARD_ALL = 0x0451,  // Set
RESET_BOARD_ALL = 0x0452,  // Set

//Strict Test Commands
BOARD_BASEEEPROM_DESTROY = 0x0460,  // W        Corrupt the BaseE2Prom

};





}

