name: Build Trion SDK C/C++ examples
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build C Examples
      run: |
        cmake -B ${{github.workspace}}/build_c -DCMAKE_BUILD_TYPE=Release trion/C
        cmake --build ${{github.workspace}}/build_c --parallel
    - name: Build C++ Examples
      run: |
        cmake -B ${{github.workspace}}/build_cxx -DCMAKE_BUILD_TYPE=Release trion/CXX
        cmake --build ${{github.workspace}}/build_cxx --parallel
    - name: Build TRIONET C Examples
      run: |
        cmake -B ${{github.workspace}}/build_trionet_c -DCMAKE_BUILD_TYPE=Release trionet/C
        cmake --build ${{github.workspace}}/build_trionet_c --parallel
